name: Build

on:
  push:
    branches:
      - workflows
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: RuboCop
        run: bundle exec rubocop

  build-and-test:
    runs-on: ubuntu-latest
    needs: lint-check
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: Clean Gems
        run: /bin/rm -f *.gem
      - name: Build Gem
        run: gem build
      - name: Push Gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
        run: gem push *.gem
